### ISSUE TITLE
Change `baseUrl` to fix the problem

### ISSUE THREAD

**Issue by leosuncin** [bscaspar/cypress-next-import-error-example#1]
The problem is caused by  
  
https://github.com/bscaspar/cypress-next-import-error-example/blob/864ede4aaa43e97587449b16eb390043f5f71a22/cypress/tsconfig.json#L6

Changing the `baseUrl` to ".." which is the root of the project will solve it

**Comment by bscaspar** [comment]
That was incredibly simple and makes sense. Thank you!!
